---
# global configuration
global:
  core: 2
  memory: 2048
  disk_size: 40140
  ssh_port: 22
  ssh_wait_timeout: 10000s

# Debian builds
debian8.10:
  vm_name: debian-8-10-jessie
  url: https://cdimage.debian.org/cdimage/archive/8.10.0/amd64/iso-cd/debian-8.10.0-amd64-netinst.iso
  md5: 19dcfc381bd3e609c6056216d203f5bc

debian9.5:
  vm_name: debian-9-5-stretch
  url: https://cdimage.debian.org/mirror/cdimage/archive/9.5.0/amd64/iso-cd/debian-9.5.0-amd64-netinst.iso
  md5: f8446a84356a6bcbf79201cc9f46063f

debian9.6:  # current release
  vm_name: debian-9-6-stretch
  url: http://mirrors.ocf.berkeley.edu/debian-cd/current/amd64/iso-cd/debian-9.6.0-amd64-netinst.iso
  md5: 0a5352e3568bc893a9f7b65192caf1e1
