---
# global configuration
global:
  core: 2
  memory: 2048
  disk_size: 40140
  post_shutdown_delay: 10s
  ssh_port: 22
  ssh_wait_timeout: 10000s
  template: templates/debian.json.j2

# Centos builds
# centos7.6: # WIP
#   vm_name: centos-7-6
#   url: http://mirrors.usc.edu/pub/linux/distributions/centos/7.6.1810/isos/x86_64/CentOS-7-x86_64-NetInstall-1810.iso
#   sha256: 19d94274ef856c4dfcacb2e7cfe4be73e442a71dd65cc3fb6e46db826040b56e
#   template: templates/redhat.json.j2

##################
# Debian builds
# Currently, all depecated bulid requires some love, due to outdated kernels.
# This means that kernel headers are no longer in Debian repository, thus we will have to use snapshot
# repository to fetch appropriate kernel header for that build version
##################
# debian8.10: #Depecated
#   vm_name: debian-8-10-jessie
#   url: https://cdimage.debian.org/cdimage/archive/8.10.0/amd64/iso-cd/debian-8.10.0-amd64-netinst.iso
#   md5: 19dcfc381bd3e609c6056216d203f5bc

# debian8.11: #Depecated
#   vm_name: debian-8-11-jessie
#   url: https://cdimage.debian.org/cdimage/archive/8.11.0/amd64/iso-cd/debian-8.11.0-amd64-netinst.iso
#   md5: b2c2e59e37baeba74b2ede1636118908

# debian9.5: #Depecated
#   vm_name: debian-9-5-stretch
#   url: https://cdimage.debian.org/mirror/cdimage/archive/9.5.0/amd64/iso-cd/debian-9.5.0-amd64-netinst.iso
#   md5: f8446a84356a6bcbf79201cc9f46063f

# debian9.6: #Depecated
#   vm_name: debian-9-6-stretch
#   url: https://cdimage.debian.org/mirror/cdimage/archive/9.6.0/amd64/iso-cd/debian-9.6.0-amd64-netinst.iso
#   md5: 0a5352e3568bc893a9f7b65192caf1e1

# debian9.7: #Depecated
#   vm_name: debian-9-7-stretch
#   url: https://cdimage.debian.org/mirror/cdimage/archive/9.7.0/amd64/iso-cd/debian-9.7.0-amd64-netinst.iso
#   md5: 02fd37846ab95fde1ca76dd5565fab1b

debian9.11:
  vm_name: debian-9-11-stretch
  url: https://cdimage.debian.org/mirror/cdimage/archive/9.11.0/amd64/iso-cd/debian-9.11.0-amd64-netinst.iso
  md5: f525f0c3f1c4ca184a604a75dabf4f71

debian10.1:
  vm_name: debian-10-1-buster
  url: https://cdimage.debian.org/mirror/cdimage/archive/10.1.0/amd64/iso-cd/debian-10.1.0-amd64-netinst.iso
  md5: b931ef8736c98704bcf519160b50fd83

debian10.3:
  vm_name: debian-10-3-buster
  url: https://cdimage.debian.org/mirror/cdimage/archive/10.3.0/amd64/iso-cd/debian-10.3.0-amd64-netinst.iso
  md5: 5956434be4b81e6376151b64ef9b1596

debian10.6:
  vm_name: debian-10-6-buster
  url: https://cdimage.debian.org/mirror/cdimage/release/current/amd64/iso-cd/debian-10.6.0-amd64-netinst.iso
  md5: 42c43392d108ed8957083843392c794b

# TODO - Need to fix templates/raid.json.j2, as raid build is currently broken
# debian9.6-raid:
#   _inherit: debian9.6
#   vm_name: debian-9-6-stretch-raid
#   template: templates/raid.json.j2
